server:
  port: 8888
spring:
  application:
    name: server-configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/objrodrigues/microservices-course-config-server
          #username: login
          #password: key
          default-label: main
          search-paths:
          - 'greeting-service*'